name: 'waroom-deployment-tracking'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  organization:
    required: true
  service:
    required: true
  integration_token:
    required: true
    description: 'input description here'
  version:
    required: true
  environment:
    required: false
  platform:
    required: true
    default: github
  description:
    required: false
  repository_owner:
    required: false
  repository_name:
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
